### PR TITLE
Direct and Inverse Mappings Owlapy objects into DL syntax in string and Manchester systax string

### PR DESCRIPTION
**Pull request by Demirrr**
Previously, 
we use the comma in [an Enumaration of Individuals](https://www.w3.org/TR/owl2-syntax/#Enumeration_of_Individuals) to seperate individuals in the DL syntax. 
Yet, such usage can lead to confusion as the meaning of comman does not indicate AND or OR,e.g. `"∃ hasParent.{F8F137 , F5M63 , F6F77}"`

```python
C = OWLObjectOneOf((OWLNamedIndividual("http://example.com/example#a"), OWLNamedIndividual("http://example.com/example#b")))
assert renderer.render(C)=="{a ⊔ b}"
```
This idea of using logical and/or also traltes to OWLDataOneOf as shown below
```python
c = OWLDataSomeValuesFrom(property=has_age,
                           filler=OWLDataIntersectionOf([OWLDataOneOf([OWLLiteral(32.5), OWLLiteral(4.5)]),
                                                         IntegerOWLDatatype]))
rendered_c = renderer.render(c)
self.assertEqual(c, parser.parse_expression(rendered_c))
self.assertEqual(rendered_c, "∃ hasAge.({32.5 ⊔ 4.5} ⊓ xsd:integer)")
```

### 1
During refactoring, found the following test
```python
c = OWLDataAllValuesFrom(property=has_age, filler=OWLDataUnionOf([owl_datatype_min_max_inclusive_restriction(40, 80), IntegerOWLDatatype]))
rendered_c = renderer.render(c)
self.assertEqual(c, parser.parse_expression(rendered_c))
self.assertEqual(rendered_c, "∀ hasAge.(xsd:integer[≥ 40 , ≤ 80] ⊔ xsd:integer)")
```
Meaning of xsd:integer[≥ 40 , ≤ 80] is also unclear. Could you please replace the the comma with logical AND @alkidbaci ?

### 2
test_owlapy_render.py and test_owlapy_parser.py should be included in test_owlapy_conversions.py
could you take care of it @LckyLke 

### 3
C and CC must be equal right ? @alkidbaci @LckyLke ?
```python
C = OWLObjectOneOf((OWLNamedIndividual("http://example.com/example#a"), OWLNamedIndividual("http://example.com/example#b")))
rendered_c = renderer.render(C)
assert rendered_c=="{a ⊔ b}" or rendered_c=="{b ⊔ a}"
print(rendered_c)
CC = OWLObjectOneOf((OWLNamedIndividual("http://example.com/example#b"), OWLNamedIndividual("http://example.com/example#a")))
print(C==CC)
```
This problem is caused by the usage of tuple instead of a set.

- [1] @alkidbaci 
- [2] done
- [3] done

### CODE REVIEW

**Comment by LckyLke** [comment]
Currently, `print(C==CC)` does only hold if we use a set as the iterable like this:
```py
C = OWLObjectOneOf({OWLNamedIndividual("http://example.com/example#a"), OWLNamedIndividual("http://example.com/example#b")})
CC = OWLObjectOneOf({OWLNamedIndividual("http://example.com/example#b"), OWLNamedIndividual("http://example.com/example#a")})
print(C==CC)
``` 

Cause the equality method of `OWLObjectOneOf` is not order independent:
```py
    def __eq__(self, other):
        if type(other) is type(self):
            return self._values == other._values
        return NotImplemented
```

so maybe we should change it? We could convert both values to sets first?

**Comment by Demirrr** [comment]
> Currently, `print(C==CC)` does only hold if we use a set as the iterable like this:
> 
> ```python
> C = OWLObjectOneOf({OWLNamedIndividual("http://example.com/example#a"), OWLNamedIndividual("http://example.com/example#b")})
> CC = OWLObjectOneOf({OWLNamedIndividual("http://example.com/example#b"), OWLNamedIndividual("http://example.com/example#a")})
> print(C==CC)
> ```
> 
> Cause the equality method of `OWLObjectOneOf` is not order independent:
> 
> ```python
>     def __eq__(self, other):
>         if type(other) is type(self):
>             return self._values == other._values
>         return NotImplemented
> ```
> 
> so maybe we should change it? We could convert both values to sets first?

[c723e7f](https://github.com/dice-group/owlapy/pull/90/commits/c723e7f8983785836c38d553279d930a21377918) fixes this at the initialization

**Comment by Demirrr** [comment]
We should refrain from returning an exception `return NotImplemented`.

**Comment by LckyLke** [comment]
test_owlapy_render.py and test_owlapy_parser.py should be merged into test_owlapy_conversions.py and then be deleted?

**Pull request merged**
