### PR TITLE
Removed unused jar files

### PR DESCRIPTION
**Pull request by alkidbaci**
- After a double check, 30 jar files seems to not have any purpose (or they are covered by other libraries). Therefore, they are removed. #74
- OWLThing added to bidi provider which is needed for mapping of class expressions.
- Added `test_owlapy_command` for testing of `owlapy` command.

### CODE REVIEW

**Comment by Demirrr** [comment]
@alkidbaci thank you <3

**Comment by Demirrr** [comment]
Could you perhaps add one or two tests about using owlapy from [terminal](https://github.com/dice-group/owlapy/blob/develop/owlapy/scripts/run.py)?

For instance, `owlapy --path_ontology ...`, then read the enriched data and check whether particular facts are there, e.g., top object property symetric etc.

**Comment by alkidbaci** [comment]
Okay

**Review by Demirrr — APPROVED** [review]
Thank you!

**Pull request merged**
